=== kgeri/ase4j/ase4j-server/src/main/resources/objectstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ase4j.googlecode.com/schema"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ase4j.googlecode.com/schema">

	<xsd:element name="objectstore">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ObjectStorageConfig"></xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>


	<xsd:complexType name="ClassConfig">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:choice maxOccurs="1" minOccurs="0">
				<xsd:element name="id" type="IdConfig" maxOccurs="1"
					minOccurs="1">
					<xsd:annotation>
						<xsd:documentation>
							The unique business key of the class.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="composite-id" type="CompositeIdConfig"
					maxOccurs="1" minOccurs="1">
					<xsd:annotation>
						<xsd:documentation>
							The composite business key of the class.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="property" type="PropertyConfig"
				maxOccurs="unbounded" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						A mapped property of the class.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="extension" type="ExtensionConfig"
				maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					The fully qualified name of the mapped class, or
					the
					simple name if the package attribute of the storage
					element was
					specified.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="PropertyConfig">
		<xsd:complexContent>
			<xsd:extension base="BasePropertyConfig">
				<xsd:sequence>
					<xsd:element name="index" type="IndexConfig" maxOccurs="1"
						minOccurs="0">
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="IdConfig">
		<xsd:complexContent>
			<xsd:extension base="BaseElementConfig">
				<xsd:sequence>
					<xsd:element name="index" type="IndexConfig"
						maxOccurs="1" minOccurs="1">
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="CompositeIdConfig">
		<xsd:sequence>
			<xsd:element name="key-property" type="KeyPropertyConfig"
				maxOccurs="unbounded" minOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						One property of the composite business key.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="IndexConfig">
		<xsd:complexContent>
			<xsd:extension base="InstanceTypeConfig">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="KeyPropertyConfig">
		<xsd:complexContent>
			<xsd:extension base="BasePropertyConfig">
				<xsd:sequence>
					<xsd:element name="index" type="IndexConfig" maxOccurs="1"
						minOccurs="1">
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="BasePropertyConfig">
		<xsd:complexContent>
			<xsd:extension base="BaseElementConfig">

				<xsd:attribute name="type" type="xsd:string" use="optional">
					<xsd:annotation>
						<xsd:documentation>
							The type of the mapped class field, or empty
							if
							it should be determined by reflection.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>


	<xsd:complexType name="BaseElementConfig">
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					The name of the mapped class field.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ExtensionConfig">
		<xsd:complexContent>
			<xsd:extension base="BaseElementConfig"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ObjectStorageConfig">
		<xsd:sequence>
            <xsd:element name="store" maxOccurs="unbounded"
            	minOccurs="1">
            	<xsd:complexType>
            		<xsd:sequence>
            			<xsd:element name="class" type="ClassConfig"
            				maxOccurs="1" minOccurs="1">
            			</xsd:element>
            			<xsd:element name="type"
            				type="InstanceTypeConfig" maxOccurs="1" minOccurs="0">
            			</xsd:element>
            		</xsd:sequence>
            		<xsd:attribute name="id" type="xsd:string"
            			use="required">
            		</xsd:attribute>
            	</xsd:complexType>
            </xsd:element>
        </xsd:sequence>
		<xsd:attribute name="package" type="xsd:string" use="optional">
		</xsd:attribute>
	</xsd:complexType>





	<xsd:complexType name="InstanceTypeConfig">
		<xsd:sequence>
			<xsd:element name="parameter" type="Parameter" maxOccurs="unbounded" minOccurs="0"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="Parameter">
		<xsd:attribute use="required" name="key" type="xsd:string"></xsd:attribute>
		<xsd:attribute use="required" name="value" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== kgeri/ase4j/ase4j-server/src/test/resources/configuration/test-ostore-dynamo.xml
<?xml version="1.0" encoding="UTF-8"?>
<objectstore xmlns="http://ase4j.googlecode.com/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ase4j.googlecode.com/schema ../../../main/resources/objectstore.xsd">

	<!-- Object mapping for FileObjectStoreImplTest -->
	<store id="test" mode="dynamic">
		<class name="dynamic.test.TestData">
			<id name="url" type="java.lang.String" >
				<index type="trie">
					<parameter key="dictionary" value="URL" />
				</index>
			</id>

			<property name="id" type="java.lang.Integer" />
			<property name="added" type="java.util.Date" />

			<extension name="extensions" />
		</class>
	</store>
</objectstore>

=== kgeri/ase4j/ase4j-server/src/test/resources/configuration/test-ostore.xml
<?xml version="1.0" encoding="UTF-8"?>
<objectstore xmlns="http://ase4j.googlecode.com/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ase4j.googlecode.com/schema ../../../main/resources/objectstore.xsd">

	<!-- Object mapping for ObjectStoreImplTest -->
	<class name="org.ogreg.ostore.ObjectStoreImplTest$TestData">
		<id name="url">
			<index type="trie">
				<parameter key="dictionary" value="URL" />
			</index>
		</id>

		<property name="id" />
		<property name="added" />
		
		<extension name="extensions" />
	</class>
	
	<!-- Object mapping for error testing -->
	<class name="java.lang.Object" />
	
	<!-- Object mapping for AssociationStoreImplTest -->
	<class name="org.ogreg.ase4j.file.FileAssociationStoreImplTest$TestData">
		<id name="url">
			<index type="trie">
				<parameter key="dictionary" value="URL" />
			</index>
		</id>

		<property name="created" />
		<property name="length" />
	</class>
	
</objectstore>
